productms.console.enabled: true
productms.console.path: /h2
productms.datasource.url: jdbc:h2:mem:productDb;DB_CLOSE_DELAY=-1
productms.datasource.username: sa
productms.datasource.password:
productms.datasource.driver: org.h2.Driver


productms.eureka.url: http://localhost:8761/eureka
productms.zipkin.url: http://localhost:9411/

message: From dev profile under product microservice